name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xugou_db"
database_id = "d90fb3c5-a5ae-4b59-b6e9-4e05de2621d6"

[version_metadata]
binding = "CF_VERSION_METADATA"
